### ISSUE TITLE
Fix API with _get_atlas()

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#10]
Maybe an inconsistency? The parameters in Calibrator._get_atlas() are not all used, are some of them meant to be passed to the future development of the util.load_calibration_lines()

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/calibrator.py#L509-L512

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/util.py#L90-L93

**Comment by cylammarco** [comment]
Are those min_wavelength and max_wavelength different from the ones in the init, which have become the property of the Calibrator?

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/calibrator.py#L44-L49

**Comment by cylammarco** [comment]
And this:

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/calibrator.py#L221

**Comment by cylammarco** [comment]
Perhaps we should use different variable names here

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/calibrator.py#L67

**Comment by jveitchmichaelis** [comment]
This functionality is implemented in the NIST atlas loader, but isn't used in the current (uncommented) code. Needs some thought as per discussion in https://github.com/jveitchmichaelis/rascal/issues/16

**Comment by cylammarco** [comment]
`_get_atlas()` is fixed. Further discussion should go to #16.
