### ISSUE TITLE
Manually adding, removing and listing arc lines (wavelength)

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#12]

**Comment by cylammarco** [comment]
For removing, which one(s) should we consider:

(1) Pick the nearest one
(2) Pick only the exact match (how many S.F.?)
(3) Remove everything within a given range

**Comment by jveitchmichaelis** [comment]
Would suggest range for now, if you know within say 5A that shouldn't affect much.

**Comment by jveitchmichaelis** [comment]
Should line addition perform bounds checks?
