### ISSUE TITLE
Fix API with _set_peaks()

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#13]
The first parameter of _set_peaks() is not used. Potentially a formerly free parameter that has now become a property of Calibrator.

https://github.com/jveitchmichaelis/rascal/blob/9e0dddfc9052028a7b48cafb7162c2d9ea62c5fa/rascal/calibrator.py#L89-L100

**Comment by jveitchmichaelis** [comment]
Just removed it, in b8387f9950cf3875ae221ed2a39e06baede7f05a
