### ISSUE TITLE
Use NIST wavelength list

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#16]
Use NIST wavelength list instead of individual elements wavelength list copied from various sources.

**Comment by jveitchmichaelis** [comment]
This partially exists - the files should be on the development branch, but it needs default filtering as there are lots of small lines and many are close together.

Arc lines (not sure which elements are in there, but the main ones are): 

https://github.com/jveitchmichaelis/rascal/blob/dev/rascal/arc_lines/nist_clean.csv

Do we:

* Filter first by line height and then by spacing
* Filter first by line spacing then by height

This also requires vacuum correction etc. which is also implemented in dev.

**Comment by cylammarco** [comment]
I guess height first, to get rid of the lines that are outside of the possible dynamic range of a detector. Then spacing, based on the num_pixel/(max_wavelength-min_wavelength) to get a guess on the resolution. Using that resolution, we run a boxcar to pick the bright ones..?

However, if we have a doublet of the same intensity... how do we "merge" them to pick the average wavelength as we would have seen in an undersampled image?

**Comment by jveitchmichaelis** [comment]
Not sure how we'd merge. This is an issue I had with trying to do this before. It's quite hard to come up with a set of rules that identifies useful lines, whilst not discarding e.g. a very strong doublet that would be useful for calibration.

Perhaps we could say that if the peaks are above a certain threshold, then we don't worry about line spacing? If the lines are so close that they're blended, it's unlikely that picking one vs the other would make an enormous difference for the calibration, since picking either peak is within the uncertainty of the instrument.

Another approach would be to mark those lines (programmatically) as possible blends and make a new line for each doublet with a location that's a weighted average of the two?

**Comment by cylammarco** [comment]
Is it reliable to apply a scipy.signal.find_peaks() over the arc lines convolved with a gaussian based on the resolution of the spectrometer. However, we can't possibly find the resolution without user's input :/

**Comment by cylammarco** [comment]
Generating "synthetic arc spectrum" may help:

```
import numpy as np
from scipy import signal
from matplotlib.pyplot import *
ion()

def gaus(x, a, b, x0, sigma):
    """
    Simple Gaussian function.
    Parameters
    ----------
    x: float or 1-d numpy array
        The data to evaluate the Gaussian over
    a: float
        the amplitude
    b: float
        the constant offset
    x0: float
        the center of the Gaussian
    sigma: float
        the width of the Gaussian
    Returns
    -------
    Array or float of same type as input (x).
    """
    return a * np.exp(-(x - x0)**2 / (2 * sigma**2)) + b

nist = np.loadtxt('nist_clean.csv', delimiter=',', dtype='str', skiprows=1)
nist_element = nist[:, 0]
nist_wavelength = nist[:, 1].astype('float')
nist_intensity = nist[:, 2].astype('float')

xe_idx = (nist_element == 'Xe')
xe_w = np.around(nist_wavelength[xe_idx], decimals=2)
xe_i = nist_intensity[xe_idx]

# Generate the equally spaced-wavelength array, and the corresponding intensity
wavelength = np.around(np.arange(min(xe_w)-500., max(xe_w)+500.01, 0.01), decimals=2)
intensity = np.zeros_like(wavelength)
intensity[np.where(np.isin(wavelength, xe_w))] = xe_i

# Convolve with gaussian, expected from the resolution
min_wavelength = 3500
max_wavelength = 8500
num_pix = 1024

# A per pixel
R = (max_wavelength - min_wavelength) / num_pix

# Nyquist sampling rate (2.3) for CCD at seeing of 1 arcsec
sigma = R * 2.3 * 1.0
x = np.arange(-100, 100.01, 0.01)
gaussian = gaus(x, a=1., b=0., x0=0., sigma=sigma)

# Convolve to simulate the arc spectrum
model_spectrum = signal.convolve(intensity, gaussian, 'same')

figure(1, figsize=(8, 8))
clf()
plot(wavelength, intensity, color='grey', label='NIST values')
plot(wavelength, model_spectrum, label='Convolved Arc')
xlabel('Vacuum Wavelength / A')
ylabel('NIST intensity')
grid()
xlim(3800, 8200)
ylim(0, 1000)
legend()
tight_layout()
```

And the resulting spectrum (wavelengths in *vacuum*) where the greys lines are the NIST lines, blue is the spectrum after involving with the estimated resolution of the spectrum:
![image](https://user-images.githubusercontent.com/2545839/81814191-5bcee800-9520-11ea-82b2-e04f7fc70749.png)

**Comment by jveitchmichaelis** [comment]
This is now done (for now) in https://github.com/jveitchmichaelis/rascal/commit/b7ec428cd449f6db27eef9a6977c9e6d1275ed40?
