### ISSUE TITLE
Simulated spectra, unit testing and test for robustness 

### ISSUE THREAD

**Issue by jveitchmichaelis** [jveitchmichaelis/rascal#22]
We should look simulated spectra for functional testing, and to characterise how robust the fits are.

What I'm not sure about is how to generate sensible values of curvature in the polynomial - @cylammarco any ideas?

**Comment by cylammarco** [comment]
This should be a good start in generating a simulated spectrum:
https://github.com/jveitchmichaelis/rascal/blob/dev/rascal/arc_lines/convolve_lines.py

For curvature, I suppose any choice of *small* coefficients beyond the second-order will not cause any problem?

**Comment by cylammarco** [comment]
#9 rolled into here.

**Comment by cylammarco** [comment]
There are some simulated spectra and unit testing set up. A robustness test is also in place, the robust_refit is not robust enough.

Closing this issue and roll the remaining robustness issue to #45.
