### ISSUE TITLE
Fix pip and poetry conflict

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#24]
pip installation runs into a dependency problem when .toml file is present.

**Comment by jveitchmichaelis** [comment]
What versions of both did you test with?

**Comment by cylammarco** [comment]
It seems to only happen with `pip install -e /local/path`. I suppose we can fix this in future releases?

**Comment by jveitchmichaelis** [comment]
Can you try this in pyproject.toml

```
[build-system]
requires = ["poetry>=0.12", "setuptools >= 40.6.0", "wheel"]
build-backend = "poetry.masonry.api"
```

This now works for me (I think).

**Comment by cylammarco** [comment]
That works! 👍

**Comment by jveitchmichaelis** [comment]
Fixed in https://github.com/jveitchmichaelis/rascal/commit/cda50f45f8ca6b083631f8738aafcb6498ae4c22
