### ISSUE TITLE
peak_utilisation fraction is sometimes off

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#37]
I think there is confusion between peak utilisation fraction and line utilisation fraction: the former is in pixel, the latter is in wavelengths. We should have two separate quantities for diagnostics.

**Comment by jveitchmichaelis** [comment]
There's now a `self.atlas_utilisation` after fitting https://github.com/jveitchmichaelis/rascal/commit/13bacdf6103dfcd69c30544c7135e3412cad99f3

**Comment by cylammarco** [comment]
It is now returned by `fit()` and `match_peaks()`.
