### ISSUE TITLE
best_error sometimes get trapped at 0.0000

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#38]
During fit, the `best_error` sometimes gets stuck at 0.0000 with the number of best inliners equal to `sample_size`, which is clearly a bad over-fit. We should have some defensive statement to avoid "perfect fit" to overtake good fit with high peak utilisation fraction.

**Comment by cylammarco** [comment]
Now set to accept best_err only if the error is larger than 1e-4, keep open as this condition may not be sufficient.

**Comment by jveitchmichaelis** [comment]
I think this is now addressed with the referenced commit, but please have a look.

**Comment by cylammarco** [comment]
This doesn't seem to be a problem anymore, close for now.
