### ISSUE TITLE
Automate PyPI publishing

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#40]
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

or use some third party Github Actions:
https://github.com/marketplace/actions/pypi-publish
https://github.com/marketplace/actions/pypi-deployment

**Comment by jveitchmichaelis** [comment]
PYPI auto-publish has been added as a github workflow item https://github.com/jveitchmichaelis/rascal/commit/59f50d439764b5109727334282fd24f545d91327
