### ISSUE TITLE
wavelength solution of the first and the last pixels should be checked against the given min/max wavelength range

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#50]
Even though ransac is checking that pix-wave solution is within the min/max wavelength range provided, the solution can still explode at the two ends of the solution.
![image](https://user-images.githubusercontent.com/2545839/161523375-d8a41306-80b7-4038-b625-76e062a740d0.png)

We should check that the first and the last pixels are both fitted within the min/max wavelength range provided.

**Comment by cylammarco** [comment]
We need to make a flow diagram of how the wavelength limits change over the various stage of configuration.

**Comment by jveitchmichaelis** [comment]
Should be fixed in f65f81f7b5bc7539026b65b9d8f092d707942410 but needs checking

**Comment by jveitchmichaelis** [comment]
Functions correctly, discovered as it breaks the Legendre fit :)
