### ISSUE TITLE
Plotting error in plot_fit in plotting.py

### ISSUE THREAD

**Issue by buckleygeer** [jveitchmichaelis/rascal#51]
Hi
In the plot.fit function there is the following code (lines 604-613)

            ax1.vlines(
                calibrator.polyval(calibrator.peaks, fit_coeff),
                np.array(spectrum)[
                    calibrator.pix_to_rawpix(calibrator.peaks).astype("int")
                ],
                vline_max,
                linestyles="dashed",
                colors="C1",
                label="Detected Peaks",
            )

I assume that the second argument is trying to treat the peaks values as integers to pass to pix_to_rawpix which is a call to interpolate.interp1d. However it doesn't actually seem to be doing this because in one of my spectra I have a peak value of 3131.02031368 and when the interpolate code compares that value against the value of 3131 I get a bounds check error from the interp1d code. I put in print statements so I could see what was happening because interp1d doesn't actually tell you what the out-of-bounds value is! I think the code needs to be (it doesn't crash when I make that change)

            ax1.vlines(
                calibrator.polyval(calibrator.peaks, fit_coeff),
                np.array(spectrum)[
                    calibrator.pix_to_rawpix(calibrator.peaks.astype("int").astype("int")
                ],
                vline_max,
                linestyles="dashed",
                colors="C1",
                label="Detected Peaks",
            )

  Thanks Liz

**Comment by jveitchmichaelis** [comment]
Thanks, I'll take a look!

I think we'd only need to cast to int once though.

**Comment by buckleygeer** [comment]
So I don't think I fixed the problem as I just had it fail in the same way on a different spectrum. I think that because the fits are not deterministic I get different peaks each time I run it and I must have got a different set of peaks which made me think I had fixed the problem. So yes you are right, casting twice makes no difference to the problem.

**Comment by buckleygeer** [comment]
So after thinking about this further I realize that an easy solution is to just eliminate the peaks that have values that exceed the upper interpolation limit.

**Comment by cylammarco** [comment]
Hi @buckleygeer, I think changing the interpolator argument to have `fill_value='extrapolate'` in line 1014-1016 of `calibrator.py` should solve the problem.

**Comment by cylammarco** [comment]
Assume the patch works.
