### ISSUE TITLE
Support configuration files

### ISSUE THREAD

**Issue by jveitchmichaelis** [jveitchmichaelis/rascal#55]
Rascal should support configuration via file, e.g. YAML which can capture everything in one go including atlas setup.

**Comment by cylammarco** [comment]
Support Atlas config file as of https://github.com/jveitchmichaelis/rascal/commit/b0baaf479c0350085b1a6f3168825a0500bb2644.

**Comment by cylammarco** [comment]
Support calibrator config file as of https://github.com/jveitchmichaelis/rascal/commit/318178cd8b78d33a12d170fa651af4bd76719ef6
