### ISSUE TITLE
Verify new peak/atlas matcher

### ISSUE THREAD

**Issue by jveitchmichaelis** [jveitchmichaelis/rascal#70]
Need to check if the updated rules for atlas matching are an improvement or not. Ideally on fits where it would actually improve the match solution. Currently updated functionality is:

* In `match_peaks` we now return a list of candidates
* Given a list of candidate atlas matches, we return all permutations that satisfy some conditions around duplicate lines, etc.
* In theory the best candidate will be chosen, and this has had some bugfixes since we last checked it.

https://github.com/jveitchmichaelis/rascal/commit/ba3750f62c11c113968cc6c1e5b084bff043450f
https://github.com/jveitchmichaelis/rascal/commit/d0eab7ff99b1e5f3cd9cdd7d704db3b0921e47fc

**Comment by cylammarco** [comment]
Added tests to check that the fits are *not* getting worse, or affected by a different order of polynomial function, or a different minimiser. See https://github.com/jveitchmichaelis/rascal/commit/68c6c10c8fa06e0224e5e0c96e00b0c89082b236.
