### ISSUE TITLE
Atlas should support element-specific intensity and distance

### ISSUE THREAD

**Issue by jveitchmichaelis** [jveitchmichaelis/rascal#74]
We should be able to set Atlas intensities on a per element basis (because intensities are relative per element) - so the constructor should take either an int or a list of int equal to the length of the elements.

**Comment by cylammarco** [comment]
The element-specific intensity filtering is done in https://github.com/jveitchmichaelis/rascal/commit/7a4fb46af258a94e99ca1fad38affd2af300f893.

It is an ill-defined problem in screening out lines based on distance per element because the confusion issue is coming from all the lines. Close for now.
