### ISSUE TITLE
Test robustness of refine_fit()

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#9]
Possibly by some Monte-Carlo method to quantify the probability of successful refit as a function of the fractional deviation of the true pfit.

**Comment by jveitchmichaelis** [comment]
Can we test this with a few SPRAT ground truths? I have the one you produced earlier, but i think this would be better if we had multiple spectra to test against.

**Comment by jveitchmichaelis** [comment]
Guess this is largely similar to https://github.com/jveitchmichaelis/rascal/issues/22
